server:
  port: 9999
myOauthServer: 
  #hostUrl: http://localhost
  hostUrl: http://localhost:8080
  #logoutUrl: ${myOauthServer.hostUrl}/signout
  logoutUrl: ${myOauthServer.hostUrl}/logout
  # directly to some1 oauth server /logout FAIL to logout
security:
  oauth2:
    sso:
        loginPath: /login
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: ${myOauthServer.hostUrl}/oauth/token
      userAuthorizationUri: ${myOauthServer.hostUrl}/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      jwt:
          keyUri: ${myOauthServer.hostUrl}/oauth/token_key
#      user-info-uri: ${myOauthServer.hostUrl}/me
#security:
#  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
#  sessions: ALWAYS
#  oauth2:
#      sso:
#        loginPath: /login
#      client:
#        clientId: ssoclient
#        clientSecret: ssosecret
#        accessTokenUri: ${myOauthServer.hostUrl}/oauth/token
#        userAuthorizationUri: ${myOauthServer.hostUrl}/oauth/authorize
#        clientAuthenticationScheme: form
#      resource:
#        jwt:
#          keyUri: ${myOauthServer.hostUrl}/oauth/token_key
securityconfig:
  logoutsuccssurl: /signout2
  permitall: /rest/**,/bb**,/logout
  deniedpage: /deny
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# MANAGEMENT HTTP SERVER (ManagementServerProperties)
#management.context-path= # Management endpoint context-path. For instance `/actuator`
management:
    context-path=/actuator

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example: DEBUG

    