security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write,openid
#      auto-approve-scopes: '.*'
#security.user.name=user # Default user name.
#security.user.password= # Password for the default user name. A random password is logged on startup by default.
#security.user.role=USER #
  user:
    name: u1
    password: aaa
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example: DEBUG